# Generated by Django 4.2.16 on 2024-10-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpsocial', '0002_chirp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='male', max_length=200),
            preserve_default=False,
        ),
    ]
