# Generated by Django 4.2.16 on 2024-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpsocial', '0003_profile_age_profile_gender_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
