# Generated by Django 4.2.16 on 2024-10-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpsocial', '0005_profile_chirp_cloudinary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
